name: Gauntlet Release

on:
  push:
    tags:
      - "@chainlink-sol-fork/gauntlet-solana-contracts@[0-9]+.[0-9]+.[0-9]"

jobs:
  release:
    name: Release Gauntlet
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Install Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build Gauntlet
        run: |
          cd gauntlet
          nix develop -c yarn install --frozen-lockfile
          nix develop -c yarn bundle
      - name: Set Env Variables
        run: echo "GAUNTLET_SOLANA_CONTRACTS=$(npm info @chainlink-sol-fork/gauntlet-solana-contracts version)" >> $GITHUB_ENV
      - name: Upload gauntlet binary to gauntlet-solana-contracts release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gauntlet/bin/gauntlet-*
          file_glob: true
          tag: |
            @chainlink-sol-fork/gauntlet-solana-contracts@${{env.GAUNTLET_SOLANA_CONTRACTS}}
          overwrite: false
