name: Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Create Release Pull Request
        uses: changesets/action@master
        id: changesets
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # The following steps only execute on publish
      - name: Build Gauntlet
        if: steps.changesets.outputs.published == 'true'
        run: cd gauntlet && yarn && yarn bundle
      - name: Set Env Variables
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "GAUNTLET_SOLANA=$(npm info @chainlink-sol-fork/gauntlet-solana version)" >> $GITHUB_ENV
          echo "GAUNTLET_SOLANA_CONTRACTS=$(npm info @chainlink-sol-fork/gauntlet-solana-contracts version)" >> $GITHUB_ENV
          echo "GAUNTLET_SERUM_MULTISIG=$(npm info @chainlink-sol-fork/gauntlet-serum-multisig version)" >> $GITHUB_ENV
      - name: Upload gauntlet binary to gauntlet-solana release
        if: steps.changesets.outputs.published == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gauntlet/bin/gauntlet-*
          file_glob: true
          tag: |
            @chainlink-sol-fork/gauntlet-solana@${{env.GAUNTLET_SOLANA}}
          overwrite: false
      - name: Upload gauntlet binary to gauntlet-solana-contracts release
        if: steps.changesets.outputs.published == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gauntlet/bin/gauntlet-*
          file_glob: true
          tag: |
            @chainlink-sol-fork/gauntlet-solana-contracts@${{env.GAUNTLET_SOLANA_CONTRACTS}}
          overwrite: false
      - name: Upload gauntlet binary to gauntlet-serum-multisig release
        if: steps.changesets.outputs.published == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gauntlet/bin/gauntlet-*
          file_glob: true
          tag: |
            @chainlink-sol-fork/gauntlet-serum-multisig@${{env.GAUNTLET_SERUM_MULTISIG}}
          overwrite: false
